include:
 - template: Terraform/Base.gitlab-ci.yml  
 - template: Jobs/SAST-IaC.gitlab-ci.yml   

stages:
 - validate
 - test
 - build
 - deploy
 - cleanup

fmt:
 extends: .terraform:fmt
 needs: []

validate:
 extends: .terraform:validate
 needs: []

build:
 extends: .terraform:build

deploy:
 extends: .terraform:deploy
 dependencies:
   - build
 when: manual
 environment:
   name: $TF_STATE_NAME
# before_script:
#   - terraform --version
#   - terraform init
# validate:
#   stage: validate
#   script:
#     - terraform validate
#     - terraform fmt -check=true
#   only:
#     - branches
# plan:
#   stage: build
#   script:
#     - terraform plan

# apply:
#   stage: deploy
#   script:
#     - terraform apply
#   dependencies:
#     - plan
#   when: manual

# destroy:
#   stage: destroy
#   script:
#     - terraform destroy
#   dependencies:
#     - apply
#   when: manual

