
server.port= 9000

springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.enabled=true

cors.allowed.origins=*
cors.allowed.mappings=/products,/product/{id},/user/{id}/fullname,/checkout

management.server.port= 9001
management.server.address= 127.0.0.1

#management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.include=info,health,metrics,prometheus,logfile
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.endpoint.info.access=read_only
#management.prometheus.metrics.export.enabled=true

logging.level.root=INFO
logging.level.com.ite.itea.ecommerce.usecase=DEBUG
logging.file.name=logfile.log
logging.file.path=logs/